/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Finbourne.Workflow.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Abstracts the kinds of Actions available in a read-only form
    /// </summary>
    [JsonConverter(typeof(ActionDetailsResponseJsonConverter))]
    [DataContract(Name = "ActionDetailsResponse")]
    public partial class ActionDetailsResponse : AbstractOpenAPISchema, IEquatable<ActionDetailsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionDetailsResponse" /> class
        /// with the <see cref="CreateChildTasksActionResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateChildTasksActionResponse.</param>
        public ActionDetailsResponse(CreateChildTasksActionResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionDetailsResponse" /> class
        /// with the <see cref="RunWorkerActionResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RunWorkerActionResponse.</param>
        public ActionDetailsResponse(RunWorkerActionResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionDetailsResponse" /> class
        /// with the <see cref="TriggerParentTaskActionResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TriggerParentTaskActionResponse.</param>
        public ActionDetailsResponse(TriggerParentTaskActionResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(CreateChildTasksActionResponse))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(RunWorkerActionResponse))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TriggerParentTaskActionResponse))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: CreateChildTasksActionResponse, RunWorkerActionResponse, TriggerParentTaskActionResponse");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `CreateChildTasksActionResponse`. If the actual instance is not `CreateChildTasksActionResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateChildTasksActionResponse</returns>
        public CreateChildTasksActionResponse GetCreateChildTasksActionResponse()
        {
            return (CreateChildTasksActionResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `RunWorkerActionResponse`. If the actual instance is not `RunWorkerActionResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RunWorkerActionResponse</returns>
        public RunWorkerActionResponse GetRunWorkerActionResponse()
        {
            return (RunWorkerActionResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `TriggerParentTaskActionResponse`. If the actual instance is not `TriggerParentTaskActionResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TriggerParentTaskActionResponse</returns>
        public TriggerParentTaskActionResponse GetTriggerParentTaskActionResponse()
        {
            return (TriggerParentTaskActionResponse)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ActionDetailsResponse {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ActionDetailsResponse.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ActionDetailsResponse
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ActionDetailsResponse</returns>
        public static ActionDetailsResponse FromJson(string jsonString)
        {
            ActionDetailsResponse newActionDetailsResponse = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newActionDetailsResponse;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CreateChildTasksActionResponse).GetProperty("AdditionalProperties") == null)
                {
                    newActionDetailsResponse = new ActionDetailsResponse(JsonConvert.DeserializeObject<CreateChildTasksActionResponse>(jsonString, ActionDetailsResponse.SerializerSettings));
                }
                else
                {
                    newActionDetailsResponse = new ActionDetailsResponse(JsonConvert.DeserializeObject<CreateChildTasksActionResponse>(jsonString, ActionDetailsResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CreateChildTasksActionResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateChildTasksActionResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RunWorkerActionResponse).GetProperty("AdditionalProperties") == null)
                {
                    newActionDetailsResponse = new ActionDetailsResponse(JsonConvert.DeserializeObject<RunWorkerActionResponse>(jsonString, ActionDetailsResponse.SerializerSettings));
                }
                else
                {
                    newActionDetailsResponse = new ActionDetailsResponse(JsonConvert.DeserializeObject<RunWorkerActionResponse>(jsonString, ActionDetailsResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RunWorkerActionResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RunWorkerActionResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TriggerParentTaskActionResponse).GetProperty("AdditionalProperties") == null)
                {
                    newActionDetailsResponse = new ActionDetailsResponse(JsonConvert.DeserializeObject<TriggerParentTaskActionResponse>(jsonString, ActionDetailsResponse.SerializerSettings));
                }
                else
                {
                    newActionDetailsResponse = new ActionDetailsResponse(JsonConvert.DeserializeObject<TriggerParentTaskActionResponse>(jsonString, ActionDetailsResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("TriggerParentTaskActionResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TriggerParentTaskActionResponse: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newActionDetailsResponse;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ActionDetailsResponse);
        }

        /// <summary>
        /// Returns true if ActionDetailsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ActionDetailsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ActionDetailsResponse input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ActionDetailsResponse
    /// </summary>
    public class ActionDetailsResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ActionDetailsResponse).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return ActionDetailsResponse.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
