/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Finbourne.Workflow.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Request to Create a new worker
    /// </summary>
    [DataContract(Name = "RunWorkerRequest")]
    public partial class RunWorkerRequest : IEquatable<RunWorkerRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunWorkerRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RunWorkerRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RunWorkerRequest" /> class.
        /// </summary>
        /// <param name="parameters">The Parameter and their values. (required).</param>
        public RunWorkerRequest(List<ParameterValue> parameters = default(List<ParameterValue>))
        {
            // to ensure "parameters" is required (not null)
            if (parameters == null)
            {
                throw new ArgumentNullException("parameters is a required property for RunWorkerRequest and cannot be null");
            }
            this.Parameters = parameters;
        }

        /// <summary>
        /// The Parameter and their values.
        /// </summary>
        /// <value>The Parameter and their values.</value>
        [DataMember(Name = "parameters", IsRequired = true, EmitDefaultValue = true)]
        public List<ParameterValue> Parameters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunWorkerRequest {\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RunWorkerRequest);
        }

        /// <summary>
        /// Returns true if RunWorkerRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RunWorkerRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RunWorkerRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Parameters == input.Parameters ||
                    this.Parameters != null &&
                    input.Parameters != null &&
                    this.Parameters.SequenceEqual(input.Parameters)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Parameters != null)
                {
                    hashCode = (hashCode * 59) + this.Parameters.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
