/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Finbourne.Workflow.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Readonly information about how the worker should be executed
    /// </summary>
    [JsonConverter(typeof(WorkerConfigurationResponseJsonConverter))]
    [DataContract(Name = "WorkerConfigurationResponse")]
    public partial class WorkerConfigurationResponse : AbstractOpenAPISchema, IEquatable<WorkerConfigurationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerConfigurationResponse" /> class
        /// with the <see cref="FailResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of FailResponse.</param>
        public WorkerConfigurationResponse(FailResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerConfigurationResponse" /> class
        /// with the <see cref="HealthCheckResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of HealthCheckResponse.</param>
        public WorkerConfigurationResponse(HealthCheckResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerConfigurationResponse" /> class
        /// with the <see cref="LuminesceViewResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of LuminesceViewResponse.</param>
        public WorkerConfigurationResponse(LuminesceViewResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerConfigurationResponse" /> class
        /// with the <see cref="SchedulerJobResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SchedulerJobResponse.</param>
        public WorkerConfigurationResponse(SchedulerJobResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerConfigurationResponse" /> class
        /// with the <see cref="SleepResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SleepResponse.</param>
        public WorkerConfigurationResponse(SleepResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(FailResponse))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(HealthCheckResponse))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(LuminesceViewResponse))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SchedulerJobResponse))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SleepResponse))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: FailResponse, HealthCheckResponse, LuminesceViewResponse, SchedulerJobResponse, SleepResponse");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `FailResponse`. If the actual instance is not `FailResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of FailResponse</returns>
        public FailResponse GetFailResponse()
        {
            return (FailResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `HealthCheckResponse`. If the actual instance is not `HealthCheckResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of HealthCheckResponse</returns>
        public HealthCheckResponse GetHealthCheckResponse()
        {
            return (HealthCheckResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `LuminesceViewResponse`. If the actual instance is not `LuminesceViewResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of LuminesceViewResponse</returns>
        public LuminesceViewResponse GetLuminesceViewResponse()
        {
            return (LuminesceViewResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SchedulerJobResponse`. If the actual instance is not `SchedulerJobResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SchedulerJobResponse</returns>
        public SchedulerJobResponse GetSchedulerJobResponse()
        {
            return (SchedulerJobResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SleepResponse`. If the actual instance is not `SleepResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SleepResponse</returns>
        public SleepResponse GetSleepResponse()
        {
            return (SleepResponse)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WorkerConfigurationResponse {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, WorkerConfigurationResponse.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of WorkerConfigurationResponse
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of WorkerConfigurationResponse</returns>
        public static WorkerConfigurationResponse FromJson(string jsonString)
        {
            WorkerConfigurationResponse newWorkerConfigurationResponse = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newWorkerConfigurationResponse;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(FailResponse).GetProperty("AdditionalProperties") == null)
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<FailResponse>(jsonString, WorkerConfigurationResponse.SerializerSettings));
                }
                else
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<FailResponse>(jsonString, WorkerConfigurationResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("FailResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into FailResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(HealthCheckResponse).GetProperty("AdditionalProperties") == null)
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<HealthCheckResponse>(jsonString, WorkerConfigurationResponse.SerializerSettings));
                }
                else
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<HealthCheckResponse>(jsonString, WorkerConfigurationResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("HealthCheckResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into HealthCheckResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(LuminesceViewResponse).GetProperty("AdditionalProperties") == null)
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<LuminesceViewResponse>(jsonString, WorkerConfigurationResponse.SerializerSettings));
                }
                else
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<LuminesceViewResponse>(jsonString, WorkerConfigurationResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("LuminesceViewResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into LuminesceViewResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SchedulerJobResponse).GetProperty("AdditionalProperties") == null)
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<SchedulerJobResponse>(jsonString, WorkerConfigurationResponse.SerializerSettings));
                }
                else
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<SchedulerJobResponse>(jsonString, WorkerConfigurationResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SchedulerJobResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SchedulerJobResponse: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SleepResponse).GetProperty("AdditionalProperties") == null)
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<SleepResponse>(jsonString, WorkerConfigurationResponse.SerializerSettings));
                }
                else
                {
                    newWorkerConfigurationResponse = new WorkerConfigurationResponse(JsonConvert.DeserializeObject<SleepResponse>(jsonString, WorkerConfigurationResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SleepResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SleepResponse: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newWorkerConfigurationResponse;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkerConfigurationResponse);
        }

        /// <summary>
        /// Returns true if WorkerConfigurationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkerConfigurationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkerConfigurationResponse input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for WorkerConfigurationResponse
    /// </summary>
    public class WorkerConfigurationResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(WorkerConfigurationResponse).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return WorkerConfigurationResponse.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
