version: "3"

services:

  workflow-sdk-csharp-preview-build:
    build: .
    container_name: workflow-sdk-csharp-preview-build
    image: finbourne/workflow-sdk-csharp-preview-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_WORKFLOW_API_URL=${FBN_BASE_API_URL}/workflow
      - FBN_APP_NAME
    volumes:
      - .:/usr/src

